### ISSUE TITLE
Change the generated Content-Type header value?

### ISSUE THREAD

**Issue by schoettl** [Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator#119]
For a spec like this:

```json
...
        "requestBody": {
          "description": "Add item to Storage Location payload",
          "content": {
            "application/json": {
              "schema": {
...
```

the generated client adds this header to the request:
```
Content-Type: application/json; charset=utf-8
```

Unfortunately, the API server rejects the request because it doesn't like the `; charset=utf-8` appendix.

Is there a simple way to make the generator omit that? Maybe a command line option I missed or by patching the generated code?

I also tried `addRequestHeader` and `setRequestHeader` in the `configSecurityScheme` hook but it seems to have no effect on the `Content-Type` header.

**Comment by NorfairKing** [comment]
I think it's time to reject that server.

Kidding aside.
This kind of thing is very sad because it's clear that the server is wrong but you still have to fix the client.
@joel-bach The least we could do is make the `Content-Type` header overridable. What do you think?

**Comment by joel-bach** [comment]
Hey @schoettl 
This is the default behavior of the [function](https://hackage.haskell.org/package/http-conduit-2.3.9/docs/Network-HTTP-Simple.html#v:setRequestBodyJSON) used to set the JSON request body. Currently, there is no way to change this behavior via configuration or similar but you should be able to either:

- Use a custom monad to change any properties of the request however you like as described [here](https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator/issues/98#issuecomment-2027230112). Doing the same in the configSecurityScheme does not work as it is applied before setting the request body.
- Change the Common.hs in the generated code to set the header after the request body is set in `doBodyCallWithConfiguration`. I would not advise going this route but since you mentioned patching the generated code I still wanted to point it out.

Hope this gets you further, let me know if it does not yield the expected results.

> This kind of thing is very sad because it's clear that the server is wrong but you still have to fix the client.

All too true 🙈

**Comment by schoettl** [comment]
Thank you both! It's sad indeed... in my experience with two API providers, there are always bugs in the server, they never stick to their spec.

For now I went with patching the generated code. It seemed much simpler as it's only a one-line change and I have have already scripts to call the code generator. It works for now. I hope the API server is at least consistent with its content type parsing...
